### PR TITLE
intro page

### PR DESCRIPTION
**Pull request by rapoulson**
_What?_
An intro page that's a little more robust

_Why?_
An attempt to provide more insight into what the runbook is and why we have it. Feedback encouraged!

cc: @JoeGermuska @katiegeorge @david-gilbert

### CODE REVIEW

**Comment by JoeGermuska** [comment]
This sentence is a little unruly:

> Device Lab Fellows might work on an independent project that gives them deep insight into one of the areas we (say VR for instance) but not know the first thing about Voice UI. 

A proposal:
> Device Lab Fellows develop deep insight into some of these platforms working on independent projects, but for other platforms, they will need an introduction or refresher.

**Comment by david-gilbert** [comment]
What about: 

# Introduction

Welcome to the Northwestern Device Lab Official Handbook!

This Runbook is your how-to guide for all things Device Lab.

A Runbook is a compilation of procedures and routines that allow any member of a team to operate their system confidently, regardless of experience with a specific area.

In the Device Lab, we have a large collection of mobile, AR/VR, and media production devices at the Device Lab, and our collection is growing as quickly as the fields we are exploring are changing! As a result, it can be tough to keep up with all the new and emerging technologies. Here in the Device Lab, Fellows work on independent projects that give them deep insights into one of the areas we are exploring. A Fellow will become an expert on a topic, and write a page in this Runbook to help those of us that might not be as experienced with their topic of choice.

Check out the pages to the left to explore how to get started on all of our emerging technologies!

The Runbook is mostly intended for internal use, but anyone interested in how we work is welcome to check it out. Think we missed something? Feel free to [make an issue](https://github.com/NUKnightLab/device-lab-runbook/issues).

**Comment by JoeGermuska** [comment]
This seems pretty good to me. We should not be capitalizing "fellow" btw. I see I was doing that too.

**Comment by rapoulson** [comment]
hehe I think I started that---"fellow" feels old timey (like "he's a jolly
good fellow") to me, but I Googled and see that it's not correct

**Pull request merged**
